version: "3"

services:
  wp:
    image: wordpress:6.4.2-php8.1-apache
    restart: always
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASS
      WORDPRESS_DB_NAME: $DB_NAME
    volumes:
      - wordpress:/var/www/html
      - ./my-plugin:/var/www/html/wp-content/plugins/my-plugin
      - ./html:/var/www/html
      - ./lab-2-24w-Gustavo-Inacio:/var/www/html/wp-content/plugins/my-censor
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_PASS
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  wordpress: